version: '3'
services:
  
  jenkins:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
       - "8080:8080"
      restart: always
      networks: 
       - automation
      volumes:
       - ./data/jenkins:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
      
   
networks: 
  automation:
    driver: bridge


